chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete', views.delete_room, name='delete_room'),
]

sasky/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

account/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

chat/models.py
from django.db import models

from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOISES_STATUS = (
        (WAITING, 'waiting'),
        (ACTIVE, 'active'),
        (CLOSED, 'closed'),
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOISES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.client} - {self.uuid}'

chat/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from account.forms import AddUserForm, EditUserForm
from account.models import User

from .models import Room


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users,
    })


@login_required
def room(request, uuid):
    return render(request, 'chat/room.html', {
        'room': Room.objects.get(uuid=uuid),
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete.room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()

        messages.success(request, 'The room was deleted.')

        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You don\'t have access to delete rooms.')

        return redirect('/chat-admin/')



@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()

    return render(request, 'chat/user_detail.html', {
        'user': user,
        'rooms': rooms
    })


@login_required
def edit_user(request, uuid):
    if request.user.has_perm('user.edit_user'):
        user = User.objects.get(pk=uuid)

        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid():
                form.save()
                messages.success(request, 'The changes was saved.')

                return redirect('/chat-admin/')
        else:
            form = EditUserForm(instance=user)

        return render(request, 'chat/edit_user.html', {
            'user': user,
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to edit users.')

        return redirect('/chat-admin/')


@login_required
def add_user(request):
    if request.user.has_perm('user.add_user'):
        if request.method == 'POST':
            form = AddUserForm(request.POST)

            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.set_password(request.POST.get('password'))
                user.save()

                if user.role == User.MANAGER:
                    group = Group.objects.get(name='Managers')
                    group.user_set.add(user)

                messages.success(request, 'The user was added.')

                return redirect('/chat-admin/')
        else:
            form = AddUserForm()

        return render(request, 'chat/add_user.html', {
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to add user.')

        return redirect('/chat-admin/')

chat/templates/chat/add_user.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl dark:text-gray-300">Add user</h1>

    <form method="post" action="">
        {% csrf_token %}

        {% for field in form %}
            <label class="dark:text-gray-300 mb-[5px]" for="{{ field.auto_id }}">{{ field.label }}:</label>
            {{ field }}
        {% endfor %}

        <button class="mt-6 inline-block py-2 px-6 bg-custom-button text-white dark:text-gray-700 dark:bg-gray-200 rounded-xl">
            Add user
        </button>
    </form>
{% endblock %}

chat/templates/chat/admin.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl dark:text-gray-300">Chat admin</h1>

    {% if perms.user.add_user %}
        <div class="mt-8">
            <h2 class="mb-4 text-lg dark:text-gray-300">Users</h2>

            <a href="{% url 'chat:add_user' %}" class="inline-block py-2 px-6 bg-custom-button text-white dark:text-gray-700 dark:bg-gray-200 rounded-xl">Add user</a>

            <div class="mt-6">
                <div class="not-prose relative bg-slate-50 rounded-xl overflow-hidden dark:bg-gray-400">
                    <div class="relative rounded-xl overflow-auto">
                        <div class="shadow-sm overflow-hidden my-8">
                            <table class="border-collapse table-fixed w-full text-xs sm:text-sm">
                              <thead>
                                <tr>
                                  <th class="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-1 text-slate-400 dark:text-gray-600 text-left">Name</th>
                                  <th class="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-1 text-slate-400 dark:text-gray-600 text-left">Email</th>
                                  <th class="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-1 text-slate-400 dark:text-gray-600 text-left hidden sm:block">Role</th>
                                  <th class="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-1 text-slate-400 dark:text-gray-600 text-left"></th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for user in users %}
                                  <tr class="{% cycle 'bg-gray-200 dark:bg-gray-300' '' %} ">
                                    <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-gray-600">
                                        <p class="sm:px-2">
                                          <a href="{% url 'chat:user_detail' user.pk %}">{{ user.name }}</a>
                                        <p>
                                    </td>
                                    <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-gray-600">
                                        <p class="sm:px-2">
                                            {{ user.email }}
                                        </p>
                                    </td>
                                    <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-gray-600 hidden sm:block">
                                        <p class="sm:px-2">
                                            {{ user.get_role_display }}
                                        </p>
                                    </td>
                                    <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-gray-600">
                                        {% if perms.user.edit_user %}
                                          <p class="px-2 text-right">
                                              <a href="{% url 'chat:edit_user' user.pk %}" class="underline">Edit</a>
                                          </p>
                                      {% endif %}
                                    </td>
                                  </tr>
                                {% endfor %}
                              </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <hr class="my-6">

    {% if rooms|length > 0 %}
    	<div class="mt-8">
            <h2 class="mb-4 text-lg dark:text-gray-300">Chats</h2>

            {% include 'chat/partials/room_list.html' %}
        </div>
    {% else %}
        <h2 class="mb-4 text-lg dark:text-gray-300">There are no chats here yet.</h2>
    {% endif %}
{% endblock %}

chat/templates/chat/edit_user.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl dark:text-gray-300">Edit user</h1>

    <form method="post" action="">
        {% csrf_token %}

        {% for field in form %}
            <label class="dark:text-gray-300 mb-[5px]" for="{{ field.auto_id }}">{{ field.label }}:</label>
            {{ field }}
        {% endfor %}

    <button class="mt-6 inline-block py-2 px-6 bg-custom-button text-white dark:text-gray-700 dark:bg-gray-200 rounded-xl">
        Save changes
    </button>
    </form>
{% endblock %}

chat/templates/chat/room.html
{% extends 'core/base.html' %}

{%  load static chatextras %}

{% block content %}
    <h1 class="text-2xl dark:text-gray-300">Chat "{{ room.uuid }}"</h1>

    <hr class="my-6">

    <p class="mb-6 dark:text-gray-300">
        <b>Name: </b>{{ room.client }}<br>
        <b>Started: </b>{{ room.created_at|timesince }} ago<br>
        <b>Status: </b>{{ room.get_status_display }}<br>
        <b>Page: </b>{{ room.url }}<br>
        <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
    </p>

    <hr class="my-6">
    <div id="chat_log" class="mb-4 p-4 bg-gray-100 dark:bg-gray-600 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for message in room.messages.all %}
            <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
                {% if not message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300 dark:bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}

                <div>
                    <div class="p-3 rounded-l-lg rounded-br-lg {% if message.created_by %}bg-blue-300{% else %}bg-gray-300 dark:bg-gray-200{% endif %}">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>

                    <span class="text-xs text-gray-500 dark:text-gray-300 leading-none">
                        {{ message.created_at|timesince }} ago
                    </span>
                </div>
                {% if message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300 dark:bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {%  if room.status != 'closed' %}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 dark:bg-gray-600 rounded-xl dark:text-gray-300 dark:placeholder-gray-400" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-custom-button text-white dark:text-gray-700 dark:bg-gray-200 rounded-xl">Send</button>
    {% endif %}
{% endblock %}

{% block scripts %}
    {% if room.status != 'closed' %}
        {{ room.uuid|json_script:'room_uuid' }}
        {{ request.user.name|json_script:'user_name' }}
        {{ request.user.id|json_script:'user_id' }}

        <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock %}

chat/templates/chat/user_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl dark:text-gray-300">{{ user.name }}</h1>

    <hr class="my-6">

    {% if rooms|length > 0 %}
        <div class="mt-8">
            <h2 class="mb-4 text-lg dark:text-gray-300">Chats</h2>

            {% include 'chat/partials/room_list.html' %}
        </div>
    {% else %}
        <h2 class="mb-4 text-lg dark:text-gray-300">There are no chats here yet.</h2>
    {% endif %}

{% endblock %}