chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete', views.delete_room, name='delete_room'),
]

sasky/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models

from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOISES_STATUS = (
        (WAITING, 'waiting'),
        (ACTIVE, 'active'),
        (CLOSED, 'closed'),
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOISES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.client} - {self.uuid}'

chat/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from account.forms import AddUserForm, EditUserForm
from account.models import User

from .models import Room


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users,
    })


@login_required
def room(request, uuid):
    return render(request, 'chat/room.html', {
        'room': Room.objects.get(uuid=uuid),
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete.room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()

        messages.success(request, 'The room was deleted.')

        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You don\'t have access to delete rooms.')

        return redirect('/chat-admin/')



@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()

    return render(request, 'chat/user_detail.html', {
        'user': user,
        'rooms': rooms
    })


@login_required
def edit_user(request, uuid):
    if request.user.has_perm('user.edit_user'):
        user = User.objects.get(pk=uuid)

        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid():
                form.save()
                messages.success(request, 'The changes was saved.')

                return redirect('/chat-admin/')
        else:
            form = EditUserForm(instance=user)

        return render(request, 'chat/edit_user.html', {
            'user': user,
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to edit users.')

        return redirect('/chat-admin/')


@login_required
def add_user(request):
    if request.user.has_perm('user.add_user'):
        if request.method == 'POST':
            form = AddUserForm(request.POST)

            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.set_password(request.POST.get('password'))
                user.save()

                if user.role == User.MANAGER:
                    group = Group.objects.get(name='Managers')
                    group.user_set.add(user)

                messages.success(request, 'The user was added.')

                return redirect('/chat-admin/')
        else:
            form = AddUserForm()

        return render(request, 'chat/add_user.html', {
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to add user.')

        return redirect('/chat-admin/')

chat/templates/chat/partials/chat_bubble.html
<div id="chat" class="max-w-[300px] fixed right-2 bottom-32 p-4 bg-white dark:bg-black border border-gray-300 dark:border-white rounded-xl z-50">
    <div id="chat_icon">
        <button id="chat_open" class="flex items-center dark:bg-black dark:text-gray-300">
            Chat Support
        </button>
    </div>

    <div id="chat_welcome" class="hidden">
        <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100 dark:bg-gray-600 dark:text-gray-300 dark:placeholder-gray-400" placeholder="Your name...">

        <button id="chat_join" class="py-2 px-6 rounded-xl text-white dark:text-gray-700 bg-custom-button dark:bg-gray-200">Join chat</button>
    </div>

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 rounded-xl h-[300px] overflow-scroll bg-gray-100 dark:bg-gray-600 dark:text-gray-300">
             <p>Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>

        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 dark:bg-gray-600 dark:text-gray-300 dark:placeholder-gray-400 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-custom-button text-white dark:text-gray-700 dark:bg-gray-200 rounded-xl">Send</button>
    </div>
</div>

chat/templates/chat/partials/room_list.html
<div class="grid grid-cols-1 sm:grid-cols-4 gap-4">
    {% for room in rooms %}
        <div class="p-4 rounded-xl {% if room.status == 'waiting' %}bg-yellow-100 dark:bg-yellow-300{% elif room.status == 'active' %}bg-emerald-100 dark:bg-emerald-400{% else %}bg-gray-100 dark:bg-gray-400{% endif %}">
            <h3 class="mb-4 text-lg text-gray-600 dark:text-gray-700">
                Chat
            </h3>

            <p class="text-gray-600 dark:text-gray-700">
                <b>ID: </b>{{ room.uuid }}<br>
                <b>Name: </b>{{ room.client }}<br>
                <b>Status: </b>{{ room.get_status_display }}<br>
                <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}<br>
            </p>

            <a href="{% url 'chat:room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-custom-button dark:border dark:border-stone-400 text-white dark:text-gray-600 dark:bg-gray-200 rounded-xl">
                {% if room.status == 'waiting' %}
                    Join
                {% elif room.status == 'closed' %}
                    Show
                {% else %}
                    Go in
                {% endif %}
            </a>
            <a href="{% url 'chat:delete_room' room.uuid %}"
                class="mt-4 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl"
                onclick="return confirm('Are you sure?');">
                Delete
            </a>
        </div>
    {% endfor %}
</div>