account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

from .forms import LoginForm

app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html', form_class=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout')
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete', views.delete_room, name='delete_room'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
]

sasky/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html', {
        'user': request.user.is_staff
    })

core/templates/core/base.html
{% load static %}

<!doctype html>

<html lang="fi">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link href="https://sasky.fi/wp-content/themes/sasky-2/dist/images/favicon-445418d420.svg" rel="icon" type="image/svg+xml">
        <title>Sasky Oma Projecti</title>
    </head>

    <body class="flex flex-col h-[100vh] dark:bg-black">
        <div class="p-2 flex-[1_0_auto]">
            <nav class="p-6 bg-gray-100 dark:bg-gray-800 text-black dark:text-gray-300 flex justify-between sm:items-center rounded-xl">
                <a href="{% url 'core:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 153 68" fill="none" class="fill-[#2B4D6E] dark:fill-amber-50 w-[110px] h-[45px] sm:w-[153px] sm:h-[68px] margin-off header__logo-image" role="img" focusable="false">
                        <path d="M.58 44.393h8.36v7.095c0 4.446 1.52 6.338 4.18 6.338 2.66 0 3.99-1.892 3.99-6.338-.096-5.582-1.616-8.798-7.126-14.663-4.94-5.298-7.505-9.46-8.645-14.19-.475-1.893-.665-3.974-.665-6.15C.674 6.268 5.044.308 13.12.308s12.16 5.771 12.16 16.366v5.96h-7.884v-6.622c0-4.446-1.426-6.433-4.18-6.433-2.756 0-4.18 2.082-4.18 6.339 0 2.365.474 4.446 1.71 6.716 1.14 2.082 2.85 4.352 5.51 7.19 6.84 7.284 9.025 12.298 9.215 20.812 0 10.028-3.895 16.65-12.446 16.65-8.55 0-12.445-5.865-12.445-16.65v-6.243zM30.536 67.16L38.041.381h12.73l7.41 66.782h-7.6l-1.425-12.976h-9.595l-1.425 12.976h-7.6v-.003zm10.07-21.846h7.6l-3.8-34.06-3.8 34.06zm22.643-.921h8.36v7.095c0 4.446 1.52 6.338 4.18 6.338 2.66 0 3.99-1.892 3.99-6.338-.095-5.582-1.615-8.798-7.125-14.663-4.94-5.298-7.505-9.46-8.645-14.19-.475-1.893-.665-3.974-.665-6.15 0-10.217 4.37-16.177 12.445-16.177 8.076 0 12.16 5.771 12.16 16.366v5.96h-7.885v-6.622c0-4.446-1.425-6.433-4.18-6.433s-4.18 2.082-4.18 6.339c0 2.365.475 4.446 1.71 6.716 1.14 2.082 2.85 4.352 5.51 7.19 6.84 7.284 9.025 12.298 9.215 20.812 0 10.028-3.894 16.65-12.445 16.65-8.55 0-12.445-5.865-12.445-16.65v-6.243zM122.052.29l-10.45 33.198 10.618 33.735h-10.121l-8.956-31.064v31.004h-8.36V.384h8.36v30.43L111.89.29h10.165-.003zm5.636.091h8.361v35.394c0 4.484 1.52 6.392 4.18 6.392 2.66 0 4.275-1.908 4.275-6.392V.38h8.075v50.278c0 10.781-4.18 16.504-12.445 16.504h-11.496v-9.539h11.401c2.66 0 4.465-1.907 4.465-6.486v-.095c-1.33.476-2.755.669-4.37.669-8.17 0-12.446-5.916-12.446-16.792V.381z"></path>
                        <title>SASKY koulutuskuntayhtymä</title>
                    </svg>
                </a>

                <div class="flex items-center space-x-4 text-sm sm:text-lg">
                    {% if user %}
                        <a href="{% url 'account:logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'account:login' %}">Login</a>
                    {% endif %}


                    {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:admin' %}" class="inline-block py-4 px-6 bg-custom-button text-white dark:text-gray-700 dark:bg-gray-200 rounded-xl">Admin</a>
                    {% endif %}
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div id="message" class="mb-6 p-6 bg-custom-button dark:text-gray-700 dark:bg-gray-200 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>

                    <script>
                        setTimeout(function() {
                            let message = document.getElementById('message');
                            message.style.transition = '.5s';
                            message.style.opacity = '0';
                            message.remove();
                        }, 3500);
                    </script>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-gray-300 text-center text-md flex-[0_0_auto] w-full flex flex-row justify-between">
            <p class="hidden sm:block">SASKY&nbsp;&nbsp;|&nbsp;&nbsp;Smyrnov Diman oma projekti&nbsp;&nbsp;|&nbsp;&nbsp;{% now 'Y' %}</p>
            <p class="block sm:hidden">SASKY, {% now 'Y' %}</p>
            <label class="inline-flex items-center cursor-pointer">
                <span class="mr-2 sm:mr-3 text-xs font-medium text-white dark:text-gray-300">
                    <svg class="w-6 h-6 text-white dark:text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5V3m0 18v-2M7.05 7.05 5.636 5.636m12.728 12.728L16.95 16.95M5 12H3m18 0h-2M7.05 16.95l-1.414 1.414M18.364 5.636 16.95 7.05M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z"></path>
                    </svg>
                </span>
                <input id="theme-choice" type="checkbox" value="" class="sr-only peer" onclick="themeToggle()">
                <div class="relative w-11 h-6 bg-gray-300 peer-focus:outline-none peer-focus:ring-2 peer-focus:white dark:peer-focus:ring-2 ring-white dark:peer-focus:ring-white rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-white peer-checked:bg-grey-700"></div>
                <span class="ml-2 sm:ml-3 text-xs font-medium text-white dark:text-gray-300">
                    <svg class="w-6 h-6 text-gray-500 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 21a9 9 0 0 1-.5-17.986V3c-.354.966-.5 1.911-.5 3a9 9 0 0 0 9 9c.239 0 .254.018.488 0A9.004 9.004 0 0 1 12 21Z"></path>
                    </svg>
                </span>
            </label>
        </footer>

        <script src="{% static 'js/theme.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
    <div class="mt-12 py-12 px-8 grid grid-cols-1 sm:grid-cols-5 gap-4 items-center border border-rose-200 dark:border-white rounded-xl">
        <div class="col-span-5 sm:col-span-2">
            <img src="{% static 'images/live-chat.jpg' %}">
        </div>

        <div class="col-span-3 sm:col-span-3">
            <h1 class="mb-8 text-xl sm:text-2xl text-center dark:text-gray-300">Smyrnov Diman oma projekti</h1>

            <h2 class="text-md text-gray-500 dark:text-gray-300 sm:text-lg p-2">
                Tämä on chat-toiminnon käyttöönotto verkkosivustolla kommunikointia varten johtajan/järjestelmänvalvojan kanssa.
            </h2>
            <h2 class="text-md text-gray-500 dark:text-gray-300 sm:text-lg p-2">
                Projektissa käytetään: Python-ohjelmointikieltä, Django-kehystä, Django Channelsin HTTP/WebSocket-palvelinta Websocketin kanssa työskentelyyn.
            </h2>
        </div>
    </div>

    {% if False == user %}
        {% include 'chat/partials/chat_bubble.html' %}
    {% endif %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}